task_name: "QuestSquirrel Task"
pipeline: [
  'hivequery','dataprocess', 'reportgenerate', 'logging'
]

connector:
  host: "172.19.121.24"
  port: "10000"
  hive_conf:
    "hive.resultset.use.unique.column.names": "false"
  username: "hadoop"
  password: "hadoop"
  auth: "CUSTOM"
  temp_save_path: "data/temp"

email:
  # message: "测试QuestSquirrel"
  message: "附件包含报表和可视化补充网页, 网页包含(用户商品购买间隔行为分析TOP20（日报）)和(用户付费频次分析（日报）)"
  subject: "第一版充值类数据统计日报优化(本邮件为程序自动发送)"
  header_from: "郭子谆"
  sender_email: "guozizhun@cxxmobi.com"
  header_to: "屠林超, 黄琎晶"
  recipient_show: "huangjinjing@cxxmobi.com"
  cc_show: "guozizhun@cxxmobi.com, 464096202@qq.com"
  # cc_show: ""
  user: "guozizhun@cxxmobi.com"
  password: "SMBz75e5chpJzsr2"
  # to_addrs: "464096202@qq.com, guozizhun@cxxmobi.com"
  to_addrs: "tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
  email_company: "qq"
  read_file_name: 'result'
  report_save_path: "data/results"
  send_file_name: '第一版充值类数据统计日报优化'
  send_visual_name: '可视化补充'

query:
  template_names: [
      "task_1"
      ,"task_1_2"
      ,"task_1_3"
      ,"task_2"
      ,"task_2_1"
      ,"task_2_2"
      ,"task_2_3"
      ,"task_4"
      ]
  info:
    req_cat: "request_1_2"
    req_iter: "iter_6"
    req_status: "dev"
  params:
    db_read: "b1_statistics"
    db_write: "guozizhun"
    start_date: "20231029"
    end_date: "20231106"
    start_dt: "20231120"
    end_dt: "20231127"
    step: 99
    status: 4

report:
  report_name: 'result'
  visual_name: 'visual.html'
  output_dir: "data/results"
  output_tasks: ['']
  final_visual_name: '可视化补充'

flag:
  hivequery: 1
  dataprocess: 1
  read_from_file_dataprocess: 1
  visual: 1
  read_from_file_visual: 1
  reportgenerate: 1
  running_tasks: [
      'task_1'
      ,'task_1_2'
      ,'task_1_3'
      ,'task_2'
      ,'task_2_1'
      ,'task_2_2_sheet1'
      ,'task_2_2_sheet2'
      ,'task_2_3'
      ,'task_4'
      ]
  logging: 0
  email: 1

task:
  task_1:
    hive_query:
      template_name: "task_1"
      read_from_file: 0
      save_to_file: 1
      save_file_name: "temp_1.csv"
      fetch_result: 1
    data_process:
      strategy_name: "StrategyA"
      read_from_file: 1
      save_to_file: 1
      temp_save_path: "data/temp"
      read_file_name: "temp_1.csv"
      save_file_name: "processed_task_1.csv"
    report_generate:
      sheet_name: "游戏流水日报"

  task_1_2:
    hive_query:
      template_name: "task_1_2"
      read_from_file: 0
      save_to_file: 1
      save_file_name: "temp_1_2.csv"
      fetch_result: 1
    data_process:
      strategy_name: "StrategyA"
      read_from_file: 1
      save_to_file: 1
      temp_save_path: "data/temp"
      read_file_name: "temp_1_2.csv"
      save_file_name: "processed_task_1_2.csv"
    report_generate:
      sheet_name: "用户付费间隔行为分析（日报）"
    visual:
      pass: "pass" 

  task_1_3:
    hive_query:
      template_name: "task_1_3"
      read_from_file: 0
      save_to_file: 1
      save_file_name: "temp_1_3.csv"
      fetch_result: 1
    data_process:
      strategy_name: "StrategyA"
      read_from_file: 1
      save_to_file: 1
      temp_save_path: "data/temp"
      read_file_name: "temp_1_3.csv"
      save_file_name: "processed_task_1_3.csv"
    visual_generate:
      graph_name: "PIE_task_3_top20_n_players"
      read_from_file: 1
      save_to_file: 1
      temp_save_path: "data/temp"
      read_file_name: "processed_task_1_3.csv"
      save_file_name: "task1_graph.html"
    report_generate:
      sheet_name: "用户商品购买间隔行为分析（日报）"

  task_2:
    hive_query:
      template_name: "task_2"
      read_from_file: 0
      save_to_file: 1
      save_file_name: "temp_2.csv"
      fetch_result: 1
    data_process:
      strategy_name: "StrategyA"
      read_from_file: 0
      save_to_file: 1
      temp_save_path: "data/temp"
      read_file_name: "temp_2.csv"
      save_file_name: "processed_task_2.csv"
    report_generate:
      sheet_name: "游戏各充值档位（日报）"

  task_2_1:
    hive_query:
      template_name: "task_2_1"
      read_from_file: 0
      save_to_file: 1
      save_file_name: "temp_2_1.csv"
      fetch_result: 1
    data_process:
      strategy_name: "StrategyA"
      read_from_file: 0
      save_to_file: 1
      temp_save_path: "data/temp"
      read_file_name: "temp_2_1.csv"
      save_file_name: "processed_task_2_1.csv"
    report_generate:
      sheet_name: "商品销量分析（日报）"

  task_2_2_sheet1:
    hive_query:
      template_name: "task_2_2"
      read_from_file: 0
      save_to_file: 1
      save_file_name: "temp_2_2.csv"
      fetch_result: 1
    data_process:
      strategy_name: "Strategy_2_2_sheet_1"
      read_from_file: 0
      save_to_file: 1
      temp_save_path: "data/temp"
      read_file_name: "temp_2_2.csv"
      save_file_name: "processed_task_2_2_sheet_1.csv"
    report_generate:
      sheet_name: "各充值档位VIP分布(日报）人数分布"

  task_2_2_sheet2:
    hive_query:
      template_name: "task_2_2"
      read_from_file: 0
      save_to_file: 1
      save_file_name: "temp_2_2.csv"
      fetch_result: 1
    data_process:
      strategy_name: "Strategy_2_2_sheet_2"
      read_from_file: 1
      save_to_file: 1
      temp_save_path: "data/temp"
      read_file_name: "temp_2_2.csv"
      save_file_name: "processed_task_2_2_sheet_2.csv"
    report_generate:
      sheet_name: "各充值档位VIP分布(日报）订单分布"

  task_2_3:
    hive_query:
      template_name: "task_2_3"
      read_from_file: 0
      save_to_file: 1
      save_file_name: "temp_2_3.csv"
      fetch_result: 1
    data_process:
      strategy_name: "StrategyA"
      read_from_file: 0
      save_to_file: 1
      temp_save_path: "data/temp"
      read_file_name: "temp_2_3.csv"
      save_file_name: "processed_task_2_3.csv"
    report_generate:
      sheet_name: "商品VIP付费情况分析（日报）"

  task_4:
    hive_query:
      template_name: "task_4"
      read_from_file: 0
      save_to_file: 1
      save_file_name: "temp_4.csv"
      fetch_result: 1
    data_process:
      strategy_name: "StrategyA"
      read_from_file: 1
      save_to_file: 1
      temp_save_path: "data/temp"
      read_file_name: "temp_4.csv"
      save_file_name: "processed_task_4.csv"
    visual_generate:
      graph_name: "BAR_task_4_top10_chargetimes_n_players"
      read_from_file: 1
      save_to_file: 1
      temp_save_path: "data/temp"
      read_file_name: "processed_task_4.csv"
      save_file_name: "task4_graph.html"
    report_generate:
      sheet_name: "用户付费频次分析（日报）"
  

log:
  log_name: 'log_'
