connector:
  host: "172.19.121.24"
  port: "10000"
  hive_conf:
    "hive.resultset.use.unique.column.names": "false"
    "hive.execution.engine": "spark"
    "spark.executor.instances": "6"
    "spark.executor.cores": "8"
    "spark.driver.cores": "8"
  username: "hadoop"
  password: "hadoop"
  auth: "CUSTOM"

test:
  launch: 0
  params:
    end_dt: '2024-04-28'
    gap_days: 8

steps: 
  query: 1
  report: 1
  visual: 1
  email: 1

module:
  connector_module: 'connector'
  query_module: 'query'
  report_module: 'report'
  visual_module: 'visual'
  email_module: 'email'
  # email_module: 'email_test'

query:
  task_fairy_1:
    temp_save_path: "data/quest_fairydemon"
    tasks_num: 8
    template_names: ['dws_mall_task1', 'dws_mall_task2' ,'dws_mall_task3' ,'dws_mall_task4', 'dws_envir_task1', 'dws_envir_task2', 'dws_envir_task3', 'dws_envir_task4']
    flags: [1, 1, 1, 1, 1, 1, 1, 1]
    # flags: [1, 1, 1, 1, 1, 1, 1, 1]
    # flags: [0, 0, 0, 0, 0, 0, 0, 0]
    tables: ['dws_mall_task1.xlsx', 'dws_mall_task2.xlsx', 'dws_mall_task3.xlsx', 'dws_mall_task4.xlsx', 'dws_envir_task1.xlsx', 'dws_envir_task2.xlsx', 'dws_envir_task3.xlsx', 'dws_envir_task4.xlsx']
    info:
      req_cat: "request_5_1"
      req_iter: "iter_2"
      req_status: "stable"
    params:
      NA: "NA"
  task_fairy_2:
    temp_save_path: "data/quest_fairydemon"
    tasks_num: 10
    template_names: [
      'dws_envir_spirit'
      ,'dws_envir_spirit_breakthru' 
      ,'dws_envir_pet'
      ,'dws_envir_pet_breakthru'
      ,'dws_envir_breakthru_level_non_operate'
      ,'dws_envir_breakthru_spirit_non_operate'
      ,'dws_envir_breakthru_level_failure'
      ,'dws_envir_breakthru_spirit_failure'
      ,'dws_envir_mall_level_interval_consumption'
      ,'dws_envir_mall_spirit_interval_consumption'
    ]
    flags: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    # flags: [0, 0, 0, 0, 0, 0, 0, 0, 1, 1]
    tables: [
      'dws_envir_spirit.xlsx'
      ,'dws_envir_spirit_breakthru.xlsx'
      ,'dws_envir_pet.xlsx'
      ,'dws_envir_pet_breakthru.xlsx'
      ,'dws_envir_breakthru_level_non_operate.xlsx'
      ,'dws_envir_breakthru_spirit_non_operate.xlsx'
      ,'dws_envir_breakthru_level_failure.xlsx'
      ,'dws_envir_breakthru_spirit_failure.xlsx'
      ,'dws_envir_mall_level_interval_consumption.xlsx'
      ,'dws_envir_mall_spirit_interval_consumption.xlsx'
    ]
    info:
      req_cat: "request_5_2"
      req_iter: "iter_1"
      req_status: "stable"
    params:
      NA: "NA"
  task_fantasy:
    temp_save_path: "data/quest_fantasy"
    tasks_num: 4
    template_names: ['dws_mall_task1', 'dws_mall_task2' ,'dws_mall_task3' ,'dws_mall_task4']
    flags: [1, 1, 1, 1]
    # flags: [0, 0, 0, 0]
    tables: ['dws_mall_task1.xlsx', 'dws_mall_task2.xlsx', 'dws_mall_task3.xlsx', 'dws_mall_task4.xlsx']
    info:
      req_cat: "request_7_1"
      req_iter: "iter_1"
      req_status: "stable"
    params:
      NA: "NA"
  task_pacific_1:
    temp_save_path: "data/quest_pacific"
    tasks_num: 8
    template_names: ['dws_mall_task1', 'dws_mall_task2', 'dws_mall_task3', 'dws_mall_task4', 'dws_envir_task1','dws_envir_task2', 'dws_envir_task3', 'dws_envir_task4']
    flags: [1, 1, 1, 1, 1, 1, 1, 1]
    # flags: [0, 0, 0, 0, 0, 0, 0, 0]
    tables: ['dws_mall_task1.xlsx', 'dws_mall_task2.xlsx', 'dws_mall_task3.xlsx', 'dws_mall_task4.xlsx', 'dws_envir_task1.xlsx', 'dws_envir_task2.xlsx', 'dws_envir_task3.xlsx', 'dws_envir_task4.xlsx']
    info:
      req_cat: "request_6_1"
      req_iter: "iter_1"
      req_status: "stable"
    params:
      na: 'na'
  task_pacific_2:
    temp_save_path: "data/quest_pacific"
    tasks_num: 3
    template_names: [
      'dws_envir_breakthru_level_failure', 
      'dws_envir_breakthru_level_non_operate',
      'dws_envir_mall_level_interval_consumption'
    ]
    flags: [1, 1, 1]
    # flags: [0, 0, 1]
    tables: [
      'dws_envir_breakthru_level_failure.xlsx'
      ,'dws_envir_breakthru_level_non_operate.xlsx'
      ,'dws_envir_mall_level_interval_consumption.xlsx'
    ]
    info:
      req_cat: "request_6_2"
      req_iter: "iter_1"
      req_status: "stable"
    params:
      na: 'na'

report:
  report_fairy:
    desc: '仙魔大陆日报1期-report-正式任务'
    temp_save_path: "data/quest_fairydemon"
    output_file: 'quest_fairydemon_result.xlsx'
    source_tables: [
      'dws_mall_task1.xlsx'
      ,'dws_mall_task2.xlsx'
      ,'dws_mall_task3.xlsx'
      ,'dws_mall_task4.xlsx'
      ,'dws_envir_task1.xlsx'
      ,'dws_envir_task2.xlsx'
      ,'dws_envir_breakthru_level_non_operate.xlsx'
      ,'dws_envir_breakthru_level_failure.xlsx'
      ,'dws_envir_mall_level_interval_consumption.xlsx'
      ,'dws_envir_task3.xlsx'
      ,'dws_envir_task4.xlsx'
      ,'dws_envir_spirit.xlsx'
      ,'dws_envir_spirit_breakthru.xlsx'
      ,'dws_envir_breakthru_spirit_non_operate.xlsx'
      ,'dws_envir_breakthru_spirit_failure.xlsx'
      ,'dws_envir_mall_spirit_interval_consumption.xlsx'
      ,'dws_envir_pet.xlsx'
      ,'dws_envir_pet_breakthru.xlsx'
    ]
    worksheet: ['ws1', 'ws2', 'ws3', 'ws4', 'ws5', 'ws6', 'ws6',
    'ws12', 'ws12',
    'ws11', 'ws11', 'ws7', 'ws8', 'ws8',
    'ws13', 'ws13',
    'ws9', 'ws10']
    ws2title:
      ws1: '仙魔大陆各模块数据大盘'
      ws2: '仙魔大陆各礼包模块'
      ws3: '仙魔各礼包ID TOP10礼包'
      ws4: '仙魔各模块中礼包ID TOP10礼包'
      ws5: '每日各境界人数分布情况'
      ws6: '境界突破情况分布'
      ws7: '各神识等级人数分布情况'
      ws8: '神识突破情况分布'
      ws9: '各灵宠等级人数分布情况'
      ws10: '灵宠突破情况分布'
      ws11: '仙魔大陆渔场消耗'
      ws12: '境界突破仅失败用用户行为分析'
      ws13: '神识突破仅失败用用户行为分析'
    column: ['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col13',
    'col14', 'col17',
    'col7', 'col8', 'col9', 'col10', 'col15',
    'col16', 'col18',
    'col11', 'col12']
    transform:
      'dws_envir_breakthru_level_failure.xlsx': ['quest_5_2_iter_1', 'LevelFailureTransform']
      'dws_envir_breakthru_spirit_failure.xlsx': ['quest_5_2_iter_1', 'SpiritFailureTransform']
      'dws_envir_mall_spirit_interval_consumption.xlsx': ['quest_5_2_iter_1', 'BreakthruSpiritFailureIntervalConsumption']
      'dws_envir_mall_level_interval_consumption.xlsx': ['quest_5_2_iter_1', 'BreakthruLevelFailureIntervalConsumption']
    col2names:
      col1: ['日期', '模块名称', '点券兑换订单数', '点券兑换金额', '仙魔大陆整体订单占比', '仙魔大陆整体金额占比', '与前一日兑换订单数对比', '与前一日点券兑换金额对比', '与前一日订单数环比', '与前一日兑换金额环比']
      col2: ['日期', '模块名称', '礼包类型', '兑换订单数', '兑换金额', '模块订单占比', '模块兑换金额占比', '与前一日兑换订单数对比', '与前一日点券兑换金额对比', '与前一日订单数环比', '与前一日兑换金额环比']
      col3: ['日期' ,'序号' ,'礼包名称' ,'礼包类型' ,'礼包单价' ,'兑换订单数' ,'兑换金额' ,'仙魔大陆总兑换订单占比' ,'仙魔大陆总兑换金额占比' ,'与前一日兑换订单数对比' ,'与前一日点券兑换金额对比' ,'与前一日订单数环比' ,'与前一日兑换金额环比']
      col4: ['日期' ,'模块名称' ,'序号' ,'礼包名称' ,'礼包单价' ,'兑换订单数' , '兑换金额' ,'仙魔大陆总兑换订单占比' ,'仙魔大陆总兑换金额占比' ,'与前一日兑换订单数对比' ,'与前一日点券兑换金额对比' ,'与前一日订单数环比' ,'与前一日兑换金额环比']
      col5: ['日期', '境界等级', '境界人数', '各境界人数与前一日对比']
      col6: ['日期', '境界等级', '经历过对应境界等级总人数', '类型', '操作总次数', '操作总人数']
      col7: ['日期' ,'总游戏人数' ,'人均游戏时长（分钟）' ,'与前一日对比' ,'总消耗金币' ,'与前一日对比' ,'净分','与前一日对比']
      col8: ['日期' ,'渔场名称' ,'渔场游戏人数' ,'人均游戏时长（分钟）' ,'与前一日对比' ,'总消耗金币' ,'消耗金币占比' ,'与前一日对比' ,'净分','与前一日对比']
      col9: ['日期', '神识等级', '神识人数', '各神识人数与前一日对比']
      col10: ['日期', '神识等级', '经历过对应神识等级总人数', '类型', '操作总次数', '操作总人数']
      col11: ['日期', '灵宠类型', '灵宠等级', '灵宠人数', '各灵宠人数与前一日对比']
      col12: ['日期', '灵宠类型', '灵宠等级', '经历过对应灵宠等级总人数', '类型', '操作总次数', '操作总人数']
      col13: ['日期', '境界等级', '未操作总人数', '活跃未操作人数']
      col14: ['日期', '境界等级', '失败次数', '失败人数', '总玩家名单', '仅购买了仙魔礼包', '购买了仙魔+常规礼包', '仅购买了常规礼包', '无任何共买记录']
      col15: ['日期', '神识等级', '未操作总人数', '活跃未操作人数']
      col16: ['日期', '神识等级','失败次数', '失败人数', '玩家名单']
      col17: ['日期', '境界等级', '等级名称', '玩家名单', '失败次数', '第几次失败', '失败时消耗材料', '礼包去重序列', '礼包', '购买订单数', '累计订单金额']
      col18: ['日期', '神识等级', '等级名称', '玩家名单', '失败次数', '第几次失败', '失败时消耗材料', '礼包去重序列', '礼包', '购买订单数', '累计订单金额']
  report_pacific:
    desc: '环太平洋日报1期'
    temp_save_path: "data/quest_pacific"
    output_file: 'result_pacific.xlsx'
    source_tables: [
      'dws_mall_task1.xlsx', 
      'dws_mall_task2.xlsx', 
      'dws_mall_task3.xlsx', 
      'dws_mall_task4.xlsx', 
      'dws_envir_task1.xlsx', 
      'dws_envir_task2.xlsx', 
      'dws_envir_breakthru_level_non_operate.xlsx',
      'dws_envir_breakthru_level_failure.xlsx',
      'dws_envir_mall_level_interval_consumption.xlsx',
      'dws_envir_task3.xlsx',
      'dws_envir_task4.xlsx'
      ]
    worksheet: [
      'ws1', 'ws2', 'ws3', 'ws4', 'ws5', 'ws6', 'ws6',
      'ws8', 'ws8',
      'ws7', 'ws7'
      ]
    ws2title:
      ws1: '环太平洋各模块数据大盘'
      ws2: '环太平洋各礼包模块'
      ws3: '环太平洋各礼包ID TOP10礼包'
      ws4: '环太平洋各模块中礼包ID TOP10礼包'
      ws5: '环太平洋每日各等级人数分布情况'
      ws6: '环太平洋突破情况分布'
      ws7: '环太平洋渔场消耗'
      ws8: '环太平洋境界突破仅失败用用户行为分析'
    column: [
      'col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col9',
      'col10', 'col11',
      'col7', 'col8'
      ]
    transform:
      'dws_envir_task4.xlsx': ['quest_6_1_iter_1', 'Envir4']
      'dws_envir_breakthru_level_failure.xlsx': ['quest_6_2_iter_1', 'LevelFailureTransform']
      'dws_envir_breakthru_level_non_operate.xlsx': ['quest_6_2_iter_1', 'BreakthruLevelNonOperate']
      'dws_envir_mall_level_interval_consumption.xlsx': ['quest_6_2_iter_1', 'BreakthruPacificFailureIntervalConsumption']
    col2names:
      col1: ['日期', '模块名称', '点券兑换订单数', '点券兑换金额', '环太平洋体订单占比', '环太平洋整体金额占比', '与前一日兑换订单数对比', '与前一日点券兑换金额对比', '与前一日订单数环比', '与前一日兑换金额环比']
      col2: ['日期', '模块名称', '礼包类型', '兑换订单数', '兑换金额', '模块订单占比', '模块兑换金额占比', '与前一日兑换订单数对比', '与前一日点券兑换金额对比', '与前一日订单数环比', '与前一日兑换金额环比']
      col3: ['日期' ,'序号' ,'礼包名称' ,'礼包类型' ,'礼包单价' ,'兑换订单数' ,'兑换金额' ,'环太平洋总兑换订单占比' ,'环太平洋总兑换金额占比' ,'与前一日兑换订单数对比' ,'与前一日点券兑换金额对比' ,'与前一日订单数环比' ,'与前一日兑换金额环比']
      col4: ['日期' ,'模块名称' ,'序号' ,'礼包名称' ,'礼包单价' ,'兑换订单数' ,'兑换金额' ,'环太平洋总兑换订单占比' ,'环太平洋总兑换金额占比' ,'与前一日兑换订单数对比' ,'与前一日点券兑换金额对比' ,'与前一日订单数环比' ,'与前一日兑换金额环比']
      col5: ['日期', '等级', '名称', '人数', '各境界人数与前一日对比']
      col6: ['日期', '名称', '经历过对应等级总人数', '类型', '操作总次数', '操作总人数']
      col7: ['日期' ,'总游戏人数' ,'与前一日对比', '人均游戏时长（分钟）' ,'与前一日对比' ,'总消耗金币' ,'与前一日对比' ,'净分', '与前一日对比']
      col8: ['日期' , '渔场id', '渔场名称' ,'渔场游戏人数' ,'与前一日对比' , '人均游戏时长（分钟）' ,'与前一日对比' ,'总消耗金币' ,'消耗金币占比' ,'与前一日对比' ,'净分', '与前一日对比']
      col9: ['日期', '等级', '等级名称', '未操作总人数', '活跃未操作人数','平均道具库存']
      col10: ['日期', '等级名称', '失败次数', '失败人数', '玩家名单']
      col11: ['日期', '清除等级', '等级名称', '玩家名单', '失败次数', '第几次失败', '失败时消耗材料', '礼包去重序列', '礼包', '购买订单数', '累计订单金额']
  report_fantasy:
    desc: '奇幻海域日报1期-report-正式任务'
    temp_save_path: "data/quest_fantasy"
    output_file: 'quest_fantasy_result.xlsx'
    source_tables: [
      'dws_mall_task1.xlsx'
      ,'dws_mall_task2.xlsx'
      ,'dws_mall_task3.xlsx'
      ,'dws_mall_task4.xlsx'
    ]
    worksheet: ['ws1', 'ws2', 'ws3', 'ws4']
    ws2title:
      ws1: '奇幻海域各模块数据大盘'
      ws2: '奇幻海域各礼包模块'
      ws3: '奇幻海域各礼包ID TOP10礼包'
      ws4: '奇幻海域各模块中礼包ID TOP10礼包'
    column: ['col1', 'col2', 'col3', 'col4']
    # transform:
    #   'dws_envir_breakthru_level_failure.xlsx': ['quest_5_2_iter_1', 'LevelFailureTransform']
    #   'dws_envir_breakthru_spirit_failure.xlsx': ['quest_5_2_iter_1', 'SpiritFailureTransform']
    #   'dws_envir_mall_level_interval_consumption.xlsx': ['quest_5_2_iter_1', 'BreakthruFailureIntervalConsumption']
    col2names:
      col1: ['日期', '模块名称', '点券兑换订单数', '点券兑换金额', '奇幻海域整体订单占比', '奇幻海域整体金额占比', '与前一日兑换订单数对比', '与前一日点券兑换金额对比', '与前一日订单数环比', '与前一日兑换金额环比']
      col2: ['日期', '模块名称', '礼包类型', '兑换订单数', '兑换金额', '模块订单占比', '模块兑换金额占比', '与前一日兑换订单数对比', '与前一日点券兑换金额对比', '与前一日订单数环比', '与前一日兑换金额环比']
      col3: ['日期' ,'序号' ,'礼包名称' ,'礼包类型' ,'礼包单价' ,'兑换订单数' ,'兑换金额' ,'奇幻海域总兑换订单占比' ,'奇幻海域总兑换金额占比' ,'与前一日兑换订单数对比' ,'与前一日点券兑换金额对比' ,'与前一日订单数环比' ,'与前一日兑换金额环比']
      col4: ['日期' ,'模块名称' ,'序号' ,'礼包名称' ,'礼包单价' ,'兑换订单数' , '兑换金额' ,'奇幻海域总兑换订单占比' ,'奇幻海域总兑换金额占比' ,'与前一日兑换订单数对比' ,'与前一日点券兑换金额对比' ,'与前一日订单数环比' ,'与前一日兑换金额环比']

visual:
  vis1:
    output_file: 'quest_fairydemon_visual.html'
    temp_save_path: "data/quest_fairydemon"
    template: 'visual_5_1_1'
    files: ['dws_mall_task1.xlsx', 'dws_mall_task2.xlsx', 'dws_mall_task3.xlsx', 'dws_mall_task4.xlsx']
  vis2:
    output_file: 'result_pacific_visual.html'
    temp_save_path: "data/quest_pacific"
    template: 'visual_6_1_1'
    files: ['dws_mall_task1.xlsx', 'dws_mall_task2.xlsx', 'dws_mall_task3.xlsx', 'dws_mall_task4.xlsx']

email_test_fantasy:
  email_fantasy:
    desc: '奇幻海域数据分析报表-email-测试任务'
    # message: "测试QuestSquirrel"
    message: "【奇幻海域商城日报-测试】附件包含报表及补充图示"
    subject: "【奇幻海域商城日报-测试】"
    header_from: "dr.who"
    sender_email: "guozizhun@cxxmobi.com"
    header_to: "guozizhun@cxxmobi.com"
    recipient_show: "[email_test]"
    cc_show: "guozizhun@cxxmobi.com, 464096202@qq.com"
    # cc_show: ""
    user: "guozizhun@cxxmobi.com"
    password: "SMBz75e5chpJzsr2"
    to_addrs: "464096202@qq.com, guozizhun@cxxmobi.com"
    # to_addrs: "tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
    email_company: "qq"
    temp_save_path: "data/quest_fantasy"
    read_file: [
      'quest_fantasy_result'
    ]
    read_file_format: ['xlsx']
    send_file: [
      '奇幻海域商城日报-测试'
    ]
    send_file_format: ['xlsx']
  email_fairy:
    desc: '捕鱼炸翻天数据分析报表-email-测试任务'
    # message: "测试QuestSquirrel"
    message: "【捕鱼炸翻天数据分析报表-测试】附件包含报表及补充图示"
    subject: "【捕鱼炸翻天数据分析报表-测试】"
    header_from: "dr.who"
    sender_email: "guozizhun@cxxmobi.com"
    header_to: "guozizhun@cxxmobi.com"
    recipient_show: "[email_test]"
    cc_show: "guozizhun@cxxmobi.com, 464096202@qq.com"
    # cc_show: ""
    user: "guozizhun@cxxmobi.com"
    password: "SMBz75e5chpJzsr2"
    to_addrs: "464096202@qq.com, guozizhun@cxxmobi.com"
    # to_addrs: "tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
    email_company: "qq"
    temp_save_path: "data/quest_fairydemon"
    read_file: [
      'quest_fairydemon_result', 
      'quest_fairydemon_visual'
    ]
    read_file_format: ['xlsx', 'html']
    # report_save_path: "data/results"
    send_file: [
      '仙魔大陆日报-测试', 
      '仙魔商城图示-测试'
    ]
    send_file_format: ['xlsx', 'html']
  email_pacific:
    desc: '环太平洋-测试'
    # message: "测试QuestSquirrel"
    message: "【环太平洋测试-测试】附件包含报表"
    subject: "【环太平洋测试-测试】环太平洋商城日报"
    header_from: "dr.guo"
    sender_email: "guozizhun@cxxmobi.com"
    header_to: "guozizhun@cxxmobi.com"
    recipient_show: "[email_test]"
    cc_show: "guozizhun@cxxmobi.com, 464096202@qq.com"
    # cc_show: ""
    user: "guozizhun@cxxmobi.com"
    password: "SMBz75e5chpJzsr2"
    to_addrs: "464096202@qq.com, guozizhun@cxxmobi.com"
    # to_addrs: "tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
    email_company: "qq"
    temp_save_path: "data/quest_pacific"
    read_file: ['result_pacific', 'result_pacific_visual']
    read_file_format: ['xlsx', 'html']
    # report_save_path: "data/results"
    send_file: ['环太平洋商城日报-测试', '环太平洋商城图示-测试']
    send_file_format: ['xlsx', 'html']

email_test:
  email1:
    desc: '捕鱼炸翻天数据分析报表-email-测试任务'
    # message: "测试QuestSquirrel"
    message: "【捕鱼炸翻天数据分析报表-测试】附件包含报表及补充图示"
    subject: "【捕鱼炸翻天数据分析报表-测试】"
    header_from: "dr.who"
    sender_email: "guozizhun@cxxmobi.com"
    header_to: "guozizhun@cxxmobi.com"
    recipient_show: "[email_test]"
    cc_show: "guozizhun@cxxmobi.com, 464096202@qq.com"
    # cc_show: ""
    user: "guozizhun@cxxmobi.com"
    password: "SMBz75e5chpJzsr2"
    to_addrs: "464096202@qq.com, guozizhun@cxxmobi.com"
    # to_addrs: "tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
    email_company: "qq"
    temp_save_path: ["data/quest_fairydemon"]
    read_file: [
      'quest_fairydemon_result', 
      'quest_fairydemon_visual',
      'quest_fantasy_result'
    ]
    read_file_format: ['xlsx', 'html', 'xlsx']
    # report_save_path: "data/results"
    send_file: [
      '仙魔大陆日报-测试', 
      '仙魔商城图示-测试',
      '奇幻海域商城日报-测试'
    ]
    send_file_format: ['xlsx', 'html', 'xlsx']
  email2:
    desc: '环太平洋-测试'
    # message: "测试QuestSquirrel"
    message: "【环太平洋测试-测试】附件包含报表"
    subject: "【环太平洋测试-测试】环太平洋商城日报"
    header_from: "dr.guo"
    sender_email: "guozizhun@cxxmobi.com"
    header_to: "guozizhun@cxxmobi.com"
    recipient_show: "[email_test]"
    cc_show: "guozizhun@cxxmobi.com, 464096202@qq.com"
    # cc_show: ""
    user: "guozizhun@cxxmobi.com"
    password: "SMBz75e5chpJzsr2"
    to_addrs: "464096202@qq.com, guozizhun@cxxmobi.com"
    # to_addrs: "tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
    email_company: "qq"
    temp_save_path: "data/quest_pacific"
    read_file: ['result_pacific', 'result_pacific_visual']
    read_file_format: ['xlsx', 'html']
    # report_save_path: "data/results"
    send_file: ['环太平洋商城日报-测试', '环太平洋商城图示-测试']
    send_file_format: ['xlsx', 'html']

email:
  email1:
    desc: '仙魔大陆1.0+2.0日报-email-正式邮件'
    # message: "测试QuestSquirrel"
    message: "【五一期间】1. 增加了每日【神识突破】中仅失败玩家自其失败尝试后的仙魔礼包购买情况汇总（玩家名单汇总，资源消耗人数汇总，礼包名称id及对应的购买订单数和累计金额）。附件包含报表及补充图示（本邮件为程序自动发送）"
    subject: "仙魔大陆商城&生态日报"
    header_from: "郭子谆"
    sender_email: "guozizhun@cxxmobi.com"
    # header_to: "屠林超, 黄琎晶"
    header_to: "张晶,顾俊,屠林超,黄琎晶"
    recipient_show: "zhangjing@cxxmobi.com, gujun@cxxmobi.com, tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
    cc_show: "guozizhun@cxxmobi.com"
    # cc_show: ""
    user: "guozizhun@cxxmobi.com"
    password: "SMBz75e5chpJzsr2"
    to_addrs: "zhangjing@cxxmobi.com, gujun@cxxmobi.com, tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
    # to_addrs: "tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
    email_company: "qq"
    temp_save_path: "data/quest_fairydemon"
    read_file: ['quest_fairydemon_result', 'quest_fairydemon_visual']
    read_file_format: ['xlsx', 'html']
    # report_save_path: "data/results"
    send_file: ['仙魔大陆商城&生态日报', '仙魔大陆商城图示']
    send_file_format: ['xlsx', 'html']
  email2:
    desc: '环太平洋1.0日报-email-正式邮件'
    # message: "测试QuestSquirrel"
    message: "【五一期间】1. 增加了每日【摧毁巢穴】中仅失败玩家自其失败尝试后的环太平洋礼包购买情况汇总（玩家名单汇总，资源消耗人数汇总，礼包名称id及对应的购买订单数和累计金额）。附件包含报表及补充图示（本邮件为程序自动发送）附件包含报表及补充图示（本邮件为程序自动发送）"
    subject: "环太平洋商城&生态日报"
    header_from: "郭子谆"
    sender_email: "guozizhun@cxxmobi.com"
    header_to: "张晶,葛茂娇,黄琎晶"
    recipient_show: "zhangjing@cxxmobi.com, gemaojiao@cxxmobi.com, huangjinjing@cxxmobi.com"
    cc_show: "guozizhun@cxxmobi.com"
    # cc_show: ""
    user: "guozizhun@cxxmobi.com"
    password: "SMBz75e5chpJzsr2"
    to_addrs: "zhangjing@cxxmobi.com, gemaojiao@cxxmobi.com, huangjinjing@cxxmobi.com"
    # to_addrs: "tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
    email_company: "qq"
    temp_save_path: "data/quest_pacific"
    read_file: ['result_pacific', 'result_pacific_visual']
    read_file_format: ['xlsx', 'html']
    # report_save_path: "data/results"
    send_file: ['环太平洋商城&生态日报', '环太平洋商城图示']
    send_file_format: ['xlsx', 'html']
  email3:
    desc: '奇幻海域数据分析报表-email-正式邮件'
    # message: "测试QuestSquirrel"
    message: "【五一期间】附件包含报表及补充图示（本邮件为程序自动发送）"
    subject: "奇幻海域商城日报"
    header_from: "郭子谆"
    sender_email: "guozizhun@cxxmobi.com"
    # header_to: "屠林超, 黄琎晶"
    header_to: "张晶,顾俊,屠林超,黄琎晶"
    recipient_show: "zhangjing@cxxmobi.com, gujun@cxxmobi.com, tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
    cc_show: "guozizhun@cxxmobi.com"
    # cc_show: ""
    user: "guozizhun@cxxmobi.com"
    password: "SMBz75e5chpJzsr2"
    to_addrs: "zhangjing@cxxmobi.com, gujun@cxxmobi.com, tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
    # to_addrs: "tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
    email_company: "qq"
    temp_save_path: "data/quest_fantasy"
    read_file: [
      'quest_fantasy_result'
    ]
    read_file_format: ['xlsx']
    send_file: [
      '奇幻海域商城日报'
    ]
    send_file_format: ['xlsx']
