connector:
  host: "172.19.121.24"
  port: "10000"
  hive_conf:
    "hive.resultset.use.unique.column.names": "false"
    "hive.execution.engine": "spark"
    "spark.executor.instances": "6"
    "spark.executor.cores": "8"
    "spark.driver.cores": "8"
  username: "hadoop"
  password: "hadoop"
  auth: "CUSTOM"

test:
  launch: 0
  params:
    end_dt: '2024-04-03'
    gap_days: 8

steps: 
  query: 1
  report: 1
  visual: 0
  email: 1

module:
  connector_module: 'connector'
  query_module: 'query_pacific_all_test'
  report_module: 'report_pacific_all_test'
  visual_module: 'visual_pacific_test'
  email_module: 'email_pacific_all_test'

query_pacific_all_test:
  task1:
    temp_save_path: "data/quest_pacific"
    tasks_num: 8
    template_names: ['dws_mall_task1', 'dws_mall_task2', 'dws_mall_task3', 'dws_mall_task4', 'dws_envir_task1','dws_envir_task2', 'dws_envir_task3', 'dws_envir_task4']
    flags: [1, 1, 1, 1, 1, 1, 1, 1]
    tables: ['dws_mall_task1.xlsx', 'dws_mall_task2.xlsx', 'dws_mall_task3.xlsx', 'dws_mall_task4.xlsx', 'dws_envir_task1.xlsx', 'dws_envir_task2.xlsx', 'dws_envir_task3.xlsx', 'dws_envir_task4.xlsx']
    info:
      req_cat: "request_6_1"
      req_iter: "iter_1"
      req_status: "dev"
    params:
      na: 'na'

report_pacific_all_test:
  report1:
    desc: '环太平洋日报1期-测试'
    temp_save_path: "data/quest_pacific"
    output_file: 'result_pacific.xlsx'
    source_tables: ['dws_mall_task1.xlsx', 'dws_mall_task2.xlsx', 'dws_mall_task3.xlsx', 'dws_mall_task4.xlsx', 'dws_envir_task1.xlsx', 'dws_envir_task2.xlsx', 'dws_envir_task3.xlsx', 'dws_envir_task4.xlsx']
    worksheet: ['ws1', 'ws2', 'ws3', 'ws4', 'ws5', 'ws6', 'ws7', 'ws7']
    ws2title:
      ws1: '环太平洋各模块数据大盘'
      ws2: '环太平洋各礼包模块'
      ws3: '环太平洋各礼包ID TOP10礼包'
      ws4: '环太平洋各模块中礼包ID TOP10礼包'
      ws5: '环太平洋每日各等级人数分布情况'
      ws6: '环太平洋突破情况分布'
      ws7: '环太平洋渔场消耗'
    column: ['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8']
    transform_module: "quest_6_1_iter_1"
    transform_class: ['na', "na", "na", "na", "na", 'na', 'na', 'T_quest_6_1_iter_1_envir_4']
    col2names:
      col1: ['日期', '模块名称', '点券兑换订单数', '点券兑换金额', '环太平洋体订单占比', '环太平洋整体金额占比', '与前一日兑换订单数对比', '与前一日点券兑换金额对比', '与前一日订单数环比', '与前一日兑换金额环比']
      col2: ['日期', '模块名称', '礼包类型', '兑换订单数', '兑换金额', '模块订单占比', '模块兑换金额占比', '与前一日兑换订单数对比', '与前一日点券兑换金额对比', '与前一日订单数环比', '与前一日兑换金额环比']
      col3: ['日期' ,'序号' ,'礼包名称' ,'礼包类型' ,'礼包单价' ,'兑换订单数' ,'兑换金额' ,'环太平洋总兑换订单占比' ,'环太平洋总兑换金额占比' ,'与前一日兑换订单数对比' ,'与前一日点券兑换金额对比' ,'与前一日订单数环比' ,'与前一日兑换金额环比']
      col4: ['日期' ,'模块名称' ,'序号' ,'礼包名称' ,'礼包单价' ,'兑换订单数' ,'兑换金额' ,'环太平洋总兑换订单占比' ,'环太平洋总兑换金额占比' ,'与前一日兑换订单数对比' ,'与前一日点券兑换金额对比' ,'与前一日订单数环比' ,'与前一日兑换金额环比']
      col5: ['日期', '等级', '名称', '人数', '各境界人数与前一日对比']
      col6: ['日期', '名称', '经历过对应等级总人数', '类型', '操作总次数', '操作总人数']
      col7: ['日期' ,'总游戏人数' ,'与前一日对比', '人均游戏时长（分钟）' ,'与前一日对比' ,'总消耗金币' ,'与前一日对比' ,'净分', '与前一日对比']
      col8: ['日期' , '渔场id', '渔场名称' ,'渔场游戏人数' ,'与前一日对比' , '人均游戏时长（分钟）' ,'与前一日对比' ,'总消耗金币' ,'消耗金币占比' ,'与前一日对比' ,'净分', '与前一日对比']

email_pacific_all_test:
  email1:
    desc: '环太平洋1期-测试'
    # message: "测试QuestSquirrel"
    message: "【环太平洋1期测试-测试】附件包含报表"
    subject: "【环太平洋1期测试-测试】环太平洋商城日报"
    header_from: "dr.guo"
    sender_email: "guozizhun@cxxmobi.com"
    header_to: "guozizhun@cxxmobi.com"
    recipient_show: "[email_test]"
    cc_show: "guozizhun@cxxmobi.com, 464096202@qq.com"
    # cc_show: ""
    user: "guozizhun@cxxmobi.com"
    password: "SMBz75e5chpJzsr2"
    to_addrs: "464096202@qq.com, guozizhun@cxxmobi.com"
    # to_addrs: "tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
    email_company: "qq"
    temp_save_path: "data/quest_pacific"
    read_file: ['result_pacific', 'result_pacific_visual']
    read_file_format: ['xlsx', 'html']
    # report_save_path: "data/results"
    send_file: ['环太平洋商城日报-测试', '太平洋商城图示-测试']
    send_file_format: ['xlsx', 'html']

visual_pacific_test:
  vis1:
    output_file: 'result_pacific_visual.html'
    temp_save_path: "data/quest_pacific"
    template: 'visual_6_1_1'
    files: ['dws_mall_task1.xlsx', 'dws_mall_task2.xlsx', 'dws_mall_task3.xlsx', 'dws_mall_task4.xlsx']