connector:
  host: "172.19.121.24"
  port: "10000"
  hive_conf:
    "hive.resultset.use.unique.column.names": "false"
    "hive.execution.engine": "spark"
    "spark.executor.instances": "6"
    "spark.executor.cores": "8"
    "spark.driver.cores": "8"
  username: "hadoop"
  password: "hadoop"
  auth: "CUSTOM"
  temp_save_path: "data/quest_fairydemon"

email:
  # message: "测试QuestSquirrel"
  message: "当此女神赐福推送日期：xxxx年xx月xx日; 对比上一次推送日期：xxxx年xx月xx日; 今日为推送日后第x日; 今日邮件包含：; 7日数据报表：新增第x日; 对比报表：有; 可视化辅助：有"
  subject: "女神赐福限时活动推送报表（推送批次xxxx年xx月xx日）"
  header_from: "郭子谆"
  sender_email: "guozizhun@cxxmobi.com"
  # header_to: "屠林超, 黄琎晶"
  header_to: "郭某测试"
  recipient_show: "huangjinjing@cxxmobi.com"
  cc_show: "guozizhun@cxxmobi.com, 464096202@qq.com"
  # cc_show: ""
  user: "guozizhun@cxxmobi.com"
  password: "SMBz75e5chpJzsr2"
  to_addrs: "464096202@qq.com, guozizhun@cxxmobi.com"
  # to_addrs: "tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
  email_company: "qq"
  read_file_name: 'result'
  report_save_path: "data/results"
  send_file_name: '第一版充值类数据统计日报优化'
  send_visual_name: '可视化补充'

query:
  tasks_num: 8
  template_names: ['dws_mall_task1', 'dws_mall_task2' ,'dws_mall_task3' ,'dws_mall_task4', 'dws_envir_task1', 'dws_envir_task2', 'dws_envir_task3', 'dws_envir_task4']
  tables: ['dws_mall_task1.xlsx', 'dws_mall_task2.xlsx', 'dws_mall_task3.xlsx', 'dws_mall_task4.xlsx', 'dws_envir_task1.xlsx', 'dws_envir_task2.xlsx', 'dws_envir_task3.xlsx', 'dws_envir_task4.xlsx']
  info:
    req_cat: "request_5_1"
    req_iter: "iter_1"
    req_status: "deliver"
  params:
    NA: "NA"