connector:
  host: "172.19.121.24"
  port: "10000"
  hive_conf:
    "hive.resultset.use.unique.column.names": "false"
    "hive.execution.engine": "spark"
    "spark.executor.instances": "2"
    "spark.executor.cores": "2"
  username: "hadoop"
  password: "hadoop"
  auth: "CUSTOM"

test:
  launch: 0
  params:
    end_dt: '2024-04-28'
    gap_days: 8

steps: 
  query: 1
  report: 1
  visual: 0
  email: 1

module:
  connector_module: 'connector'
  query_module: 'query'
  report_module: 'report'
  visual_module: 'visual'
  # email_module: 'email'
  email_module: 'email_test'

query:
  task_spark_update:
    type: 'spark'
    template_type: 'stable'
    tables:
      # - [1, 'data/quest_goddess', 'qquest_goddess_2_1_iter_5', 'GoddessPush', 'step1_push_overwrite.xlsx', {'req_cat': "request_2_1", 'req_iter': "iter_5", 'req_status': "stable"}, {'debug': 1, 'rk': 1}]
      - [1, 'data/quest_goddess', 'qquest_goddess_2_1_iter_5', 'GoddessPush', 'step1_push_overwrite.xlsx', {'req_cat': "request_2_1", 'req_iter': "iter_5", 'req_status': "stable"}, {'na':'na'}]
  task_spark:
    type: 'spark'
    template_type: 'stable'
    tables: 
  #     - [0, 'data/quest_goddess', 'qquest_goddess_2_1_iter_5', 'Task1', 'step2_task_1_1.xlsx', {'req_cat': "request_2_1", 'req_iter': "iter_5", 'req_status': "stable"}, {'debug': 1, 'l_rk': 15, 'h_rk': 16}]
  #     - [0, 'data/quest_goddess', 'qquest_goddess_2_1_iter_5', 'Task2', 'step2_task_2.xlsx', {'req_cat': "request_2_1", 'req_iter': "iter_5", 'req_status': "stable"}, {'debug': 1, 'l_rk': 15, 'h_rk': 16}]
  #     - [0, 'data/quest_goddess', 'qquest_goddess_2_1_iter_5', 'Task3', 'step2_task_3.xlsx', {'req_cat': "request_2_1", 'req_iter': "iter_5", 'req_status': "stable"}, {'debug': 1, 'l_rk': 15, 'h_rk': 16}]
  #     - [0, 'data/quest_goddess', 'qquest_goddess_2_1_iter_5', 'Task4_1', 'step2_task_4_1.xlsx', {'req_cat': "request_2_1", 'req_iter': "iter_5", 'req_status': "stable"}, {'debug': 1, 'l_rk': 15, 'h_rk': 16}]
  #     - [0, 'data/quest_goddess', 'qquest_goddess_2_1_iter_5', 'Task4_2', 'step2_task_4_2.xlsx', {'req_cat': "request_2_1", 'req_iter': "iter_5", 'req_status': "stable"}, {'debug': 1, 'l_rk': 15, 'h_rk': 16}]
      
      - [1, 'data/quest_goddess', 'qquest_goddess_2_1_iter_5', 'Task1', 'step2_task_1_1.xlsx', {'req_cat': "request_2_1", 'req_iter': "iter_5", 'req_status': "stable"}, {'na':'na'}]
      - [1, 'data/quest_goddess', 'qquest_goddess_2_1_iter_5', 'Task2', 'step2_task_2.xlsx', {'req_cat': "request_2_1", 'req_iter': "iter_5", 'req_status': "stable"}, {'na':'na'}]
      - [1, 'data/quest_goddess', 'qquest_goddess_2_1_iter_5', 'Task3', 'step2_task_3.xlsx', {'req_cat': "request_2_1", 'req_iter': "iter_5", 'req_status': "stable"}, {'na':'na'}]
      - [1, 'data/quest_goddess', 'qquest_goddess_2_1_iter_5', 'Task4_1', 'step2_task_4_1.xlsx', {'req_cat': "request_2_1", 'req_iter': "iter_5", 'req_status': "stable"}, {'na':'na'}]
      - [1, 'data/quest_goddess', 'qquest_goddess_2_1_iter_5', 'Task4_2', 'step2_task_4_2.xlsx', {'req_cat': "request_2_1", 'req_iter': "iter_5", 'req_status': "stable"}, {'na':'na'}]

report:
  report_goddess:
    desc: 'goddess日报1期-report-正式任务'
    temp_save_path: "data/quest_goddess"
    output_file: 'quest_goddess_result.xlsx'
    source_tables: [
      'step2_task_1_1.xlsx'
      ,'step2_task_2.xlsx'
      ,'step2_task_3.xlsx'
      ,'step2_task_4_1.xlsx'
      ,'step2_task_4_2.xlsx'
    ]
    worksheet: ['ws1', 'ws1', 'ws1', 'ws2', 'ws2']
    ws2title:
      ws1: '推送人群付费转化统计'
      ws2: '7日付费人数金额及占比'
    column: ['colna', 'colna', 'colna', 'colna', 'colna']
    transform:
      'step2_task_1_1.xlsx': ['quest_goddess_iter_5', 'Task1']
      'step2_task_2.xlsx': ['quest_goddess_iter_5', 'Task2']
      'step2_task_3.xlsx': ['quest_goddess_iter_5', 'Task3']
      'step2_task_4_1.xlsx': ['quest_goddess_iter_5', 'Task4_1']
      'step2_task_4_2.xlsx': ['quest_goddess_iter_5', 'Task4_1']
    col2names:
      colna: 'na'

visual:
  ZFT_Fairy:
    output_file: 'quest_fairydemon_visual.html'
    temp_save_path: "data/quest_fairydemon"
    title: '捕鱼炸翻天-仙魔大陆商城图示'
    visualizer: 
      - [1, 'vquest_5_1_iter_1', 'FairydemonMall', 'dws_mall_task1.xlsx', 'dws_mall_task2.xlsx', 'dws_mall_task3.xlsx', 'dws_mall_task4.xlsx']
      - [1, 'vquest_5_2_iter_1', 'VipFisheryDistributionVis', 'dws_envir_fishery_vip.xlsx']
  ZFT_Fantasy:
    output_file: 'quest_fantasy_visual.html'
    temp_save_path: "data/quest_fantasy"
    title: '捕鱼炸翻天-奇幻海域商城图示'
    visualizer: 
      - [1, 'vquest_5_2_iter_1', 'FantasyMall', 'dws_mall_task1.xlsx', 'dws_mall_task2.xlsx', 'dws_mall_task3.xlsx', 'dws_mall_task4.xlsx']
  YJBY_Pacific:
    output_file: 'result_pacific_visual.html'
    temp_save_path: "data/quest_pacific"
    title: '姚记捕鱼-环太平洋商城图示'
    visualizer: 
      - [1, 'vquest_6_1_iter_1', 'PacificMall', 'dws_mall_task1.xlsx', 'dws_mall_task2.xlsx', 'dws_mall_task3.xlsx', 'dws_mall_task4.xlsx']
      - [1, 'vquest_6_2_iter_1', 'VipFisheryDistributionVis', 'dws_envir_fishery_vip.xlsx']
  YJBY_Doupo:
    output_file: 'quest_doupo_visual.html'
    temp_save_path: "data/quest_doupo"
    title: '捕鱼炸翻天-斗破沧海商城图示'
    visualizer: 
      - [1, 'vquest_6_3_iter_1', 'DoupoMall', 'dws_mall_task1.xlsx', 'dws_mall_task2.xlsx', 'dws_mall_task3.xlsx', 'dws_mall_task4.xlsx']

email_test:
  email1:
    desc: '捕鱼炸翻天数据分析报表-email-测试任务'
    # message: "测试QuestSquirrel"
    message: "
    附件包含【女神赐福】推送的最新批次和上一批次的数据报表
    （本邮件为程序自动发送）"
    subject: "【捕鱼炸翻天女神赐福-测试】"
    header_from: "dr.guo"
    sender_email: "guozizhun@cxxmobi.com"
    header_to: "guozizhun@cxxmobi.com"
    recipient_show: "[email_test]"
    cc_show: "guozizhun@cxxmobi.com, 464096202@qq.com"
    # cc_show: ""
    user: "guozizhun@cxxmobi.com"
    password: "SMBz75e5chpJzsr2"
    to_addrs: "464096202@qq.com, guozizhun@cxxmobi.com"
    # to_addrs: "tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
    email_company: "qq"
    attachment_file_read_save: 
      "data/quest_goddess":
        - ['quest_goddess_result.xlsx', '女神赐福活动报表.xlsx']

email:
  email1:
    desc: '捕鱼炸翻天-email-正式邮件'
    # message: "测试QuestSquirrel"
    # message 段落
    message: "
    附件包含【女神赐福】推送的最新批次和上一批次的数据报表
    （本邮件为程序自动发送）"
    subject: "捕鱼炸翻天女神赐福"
    header_from: "郭子谆"
    sender_email: "guozizhun@cxxmobi.com"
    # header_to: "屠林超, 黄琎晶"
    header_to: "张晶,顾俊,屠林超,黄琎晶"
    recipient_show: "zhangjing@cxxmobi.com, gujun@cxxmobi.com, tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
    cc_show: "guozizhun@cxxmobi.com"
    # cc_show: ""
    user: "guozizhun@cxxmobi.com"
    password: "SMBz75e5chpJzsr2"
    to_addrs: "zhangjing@cxxmobi.com, gujun@cxxmobi.com, tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
    # to_addrs: "tulinchao@cxxmobi.com, huangjinjing@cxxmobi.com"
    email_company: "qq"
    attachment_file_read_save: 
      "data/quest_goddess":
        - ['quest_goddess_result.xlsx', '女神赐福活动报表.xlsx']